server:
  port: 8080
spring:
  application:
    name: magazine

management:
  endpoint:
    sessions:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["httpexchanges", "prometheus", "health"]

