server:
  port: 8765

spring:
  application:
    name: GateWayMagNWare

management:
  endpoints:
    web:
      exposure:
        include: ["metrics", "prometheus", "health"]

#cloud:
#  gateway:
#    routes:
#      - id: magazine
#        uri: http://localhost:8080/
#        predicates:
#          - Path=/magazineService/**
#      - id: warehouse
#        uri: http://localhost:8090/
#        predicates:
#          - Path=/warehouseService/**




